name: One-Off Task for Pathways
description: A task that supports the Pathways project
title: "[Task] <Title of task>"
labels: ["Pathways", "Pathways: Task"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping! Please add an appropriate title, then fill in the form.

  - type: textarea
    id: what_needs_to_happen
    attributes:
      label: What needs to happen?
      placeholder: Specific actions needed for this task
    validations:
      required: true

  - type: textarea
    id: why_matters
    attributes:
      label: Why this matters
      placeholder: How does this task support the Pathways project?

  - type: textarea
    id: notes
    attributes:
      label: Context
      placeholder: Any additional context, links to relavant guides, constraints, and acceptance criteria

  - type: dropdown
    id: skills_needed
    attributes:
      label: Skills needed
      options:
        - Design
        - Test
        - Build
        - Write
        - Promote
        - Organize
    validations:
      required: true

  - type: dropdown
    id: beginner_friendly
    attributes:
      label: Is this task beginner friendly?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
