name: Add label & header to new guide issues

on:
  issues:
    types: [opened]

jobs:
  setup-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'new-pathway')
    steps:
      - name: Add header and label by function
        uses: actions/github-script@v7
        with:
          script: |
            const header = '## [Create a guide](https://make.wordpress.org/handbook/pathways/write/create-a-pathway-guide/) using these details:\n\n';
            const body = context.payload.issue.body;
            const functionMatch = body.match(/### Function\n\n(.*)/);
            
            // Prepend header
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: header + body
            });
            
            // Add function label
            if (functionMatch) {
              const func = functionMatch[1].trim().toLowerCase();
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [func]
              });
            }
